name: DEVOPS PRACTISE

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: echo "HELLO I am DevOps Engineer"

  test:
    needs: build
    name: EXAMPLE TEST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        run: echo "Hello people"

  deploy:
    needs: test
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: echo "Hello India"